Repository DakaraProject/dakara-server, pull requests merged in 2018-05, with the labels that each got.

#59 Update the config example file
  config.yaml.example
Labels: documentation

#61 Extend research to all text fields in Song object
  dakara_server/library/base_test.py
  dakara_server/library/tests_song.py
  dakara_server/library/views.py
Labels: enhancement

#62 Simplify serializers
  CHANGELOG.md
  dakara_server/library/migrations/0005_auto_20180509_1916.py
  dakara_server/library/models.py
  dakara_server/library/permissions.py
  dakara_server/library/serializers.py
  dakara_server/library/tests_song.py
  dakara_server/library/tests_song_tag.py
  dakara_server/library/views.py
  dakara_server/playlist/base_test.py
  dakara_server/playlist/management/commands/createplayer.py
  dakara_server/playlist/permissions.py
  dakara_server/playlist/serializers.py
  dakara_server/playlist/serializers_device.py
  dakara_server/playlist/tests_playlist_entry.py
  dakara_server/playlist/views.py
  dakara_server/playlist/views_device.py
  dakara_server/users/models.py
  dakara_server/users/permissions.py
  dakara_server/users/serializers.py
  dakara_server/users/tests.py
  dakara_server/users/views.py
Labels: refactor
