Repository DakaraProject/dakara-server, pull requests merged in 2019-12, with the labels that each got.

#96 External Feeder
  CHANGELOG.md
  README.md
  dakara_server/dakara_server/urls.py
  dakara_server/library/management/commands/components/default_work_parser.py
  dakara_server/library/management/commands/createworks.py
  dakara_server/library/management/commands/feed.py
  dakara_server/library/management/commands/feed_components/ffmpeg_wrapper.py
  dakara_server/library/management/commands/feed_components/metadata_parser.py
  dakara_server/library/management/commands/feed_components/progress_bar.py
  dakara_server/library/management/commands/feed_components/subtitle_parser.py
  dakara_server/library/management/commands/feed_components/utils.py
  dakara_server/library/management/commands/replacedirectory.py
  dakara_server/library/migrations/0008_auto_20190609_0705.py
  dakara_server/library/models.py
  dakara_server/library/serializers.py
  dakara_server/library/tests/parser_test.py
  dakara_server/library/tests/parser_test_no_work_type.py
  dakara_server/library/tests/test_command_feed.py
  dakara_server/library/tests/test_feeder.py
  dakara_server/library/tests/test_is_similar.py
  dakara_server/library/tests/test_song.py
  dakara_server/library/tests/test_subtitle_parse.py
  dakara_server/library/tests/tests_ressources/is_similar.csv
  dakara_server/library/tests/tests_ressources/lyrics_embedded.mkv
  dakara_server/library/tests/tests_ressources/lyrics_embedded.mkv_expected
  dakara_server/library/tests/tests_ressources/subtitles/comment_and_whitespace.ass
  dakara_server/library/tests/tests_ressources/subtitles/comment_and_whitespace.ass_expected
  dakara_server/library/tests/tests_ressources/subtitles/double_lines.ass
  dakara_server/library/tests/tests_ressources/subtitles/double_lines.ass_expected
  dakara_server/library/tests/tests_ressources/subtitles/drawing_commands.ass
  dakara_server/library/tests/tests_ressources/subtitles/drawing_commands.ass_expected
  dakara_server/library/tests/tests_ressources/subtitles/simple.ass
  dakara_server/library/tests/tests_ressources/subtitles/simple.ass_expected
  dakara_server/library/views.py
  dakara_server/library/views_feeder.py
  requirements.txt
Labels: enhancement

#114 Fix bump version script
  bump_version.sh
Labels: bug, release

#116 Improve readme
  README.md
Labels: documentation

#115 Fix crash with 2 works with same title
  CHANGELOG.md
  dakara_server/library/serializers.py
  dakara_server/library/tests/test_song.py
Labels: bug
